#!/usr/bin/env python3
"""Reconcile historically dropped proposed_nodes from PM tasks.

Between 2026-04-15 and present, ~94 PM-proposed_nodes were generated by
auto-chains but silently dropped because node_state persistence was missing.
This script scans task_registry result_json for proposed_nodes and inserts
missing ones as waived into node_state.

Usage:
    # Dry-run (default): emit report to docs/dev/scratch/
    python scripts/reconcile-dropped-nodes.py

    # Live run: insert missing nodes
    python scripts/reconcile-dropped-nodes.py --no-dry-run

    # Custom workspace
    python scripts/reconcile-dropped-nodes.py --workspace /path/to/repo
"""

import argparse
import json
import os
import sqlite3
import sys
from datetime import datetime


CUTOFF_DATE = "2026-04-15"
PROJECT_ID = "aming-claw"
WAIVE_REASON = "reconcile_apr15_dropped_proposed_nodes"


def parse_args(argv=None):
    parser = argparse.ArgumentParser(
        description="Reconcile dropped proposed_nodes from PM tasks"
    )
    parser.add_argument(
        "--dry-run",
        default=True,
        action="store_true",
        dest="dry_run",
        help="Only report dropped nodes (default: True)",
    )
    parser.add_argument(
        "--no-dry-run",
        action="store_false",
        dest="dry_run",
        help="Actually insert missing nodes into node_state",
    )
    parser.add_argument(
        "--workspace",
        default=".",
        help="Workspace root to locate governance.db (default: '.')",
    )
    return parser.parse_args(argv)


def get_db_path(workspace):
    """Locate governance.db relative to workspace root."""
    db_path = os.path.join(workspace, "governance.db")
    if not os.path.exists(db_path):
        raise FileNotFoundError(f"governance.db not found at {db_path}")
    return db_path


def fetch_pm_tasks_with_proposed_nodes(conn):
    """R1: Query PM-type tasks completed since CUTOFF_DATE with proposed_nodes."""
    cursor = conn.execute(
        """
        SELECT task_id, result_json, completed_at
        FROM tasks
        WHERE type = 'pm'
          AND status = 'succeeded'
          AND completed_at >= ?
          AND result_json IS NOT NULL
        ORDER BY completed_at
        """,
        (CUTOFF_DATE,),
    )
    results = []
    for row in cursor.fetchall():
        task_id, result_json_str, completed_at = row
        try:
            result = json.loads(result_json_str)
        except (json.JSONDecodeError, TypeError):
            continue
        proposed_nodes = result.get("proposed_nodes")
        if proposed_nodes and isinstance(proposed_nodes, list):
            results.append({
                "task_id": task_id,
                "completed_at": completed_at,
                "proposed_nodes": proposed_nodes,
            })
    return results


def find_dropped_nodes(conn, pm_tasks):
    """R2: Cross-reference proposed_nodes against node_state to find dropped ones."""
    dropped = []
    for task in pm_tasks:
        for node in task["proposed_nodes"]:
            node_id = node.get("node_id")
            if not node_id:
                continue
            cursor = conn.execute(
                "SELECT 1 FROM node_state WHERE node_id = ? AND project_id = ?",
                (node_id, PROJECT_ID),
            )
            if cursor.fetchone() is None:
                dropped.append({
                    "node_id": node_id,
                    "title": node.get("title", ""),
                    "description": node.get("description", ""),
                    "source_task": task["task_id"],
                    "completed_at": task["completed_at"],
                })
    return dropped


def generate_report(dropped, workspace):
    """R3: Emit a dated markdown report with counts and sample entries."""
    today = datetime.now().strftime("%Y-%m-%d")
    report_dir = os.path.join(workspace, "docs", "dev", "scratch")
    os.makedirs(report_dir, exist_ok=True)
    report_path = os.path.join(
        report_dir, f"reconcile-dropped-nodes-{today}.md"
    )

    lines = [
        f"# Reconcile Dropped Nodes Report ({today})",
        "",
        f"**Total dropped nodes found:** {len(dropped)}",
        "",
    ]

    if dropped:
        lines.append("## Sample Entries (first 5)")
        lines.append("")
        for entry in dropped[:5]:
            lines.append(f"- **{entry['node_id']}**: {entry['title']}")
            lines.append(f"  - Source task: `{entry['source_task']}`")
            lines.append(f"  - Completed: {entry['completed_at']}")
            lines.append("")

    with open(report_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    return report_path


def insert_dropped_nodes(conn, dropped):
    """R4: Insert missing proposed_nodes into node_state as waived."""
    now = datetime.now().isoformat()
    inserted = 0
    for entry in dropped:
        evidence = json.dumps({
            "waive_reason": WAIVE_REASON,
            "source_task": entry["source_task"],
            "original_title": entry["title"],
        })
        try:
            conn.execute(
                """
                INSERT INTO node_state
                    (project_id, node_id, verify_status, build_status,
                     evidence_json, updated_by, updated_at, version)
                VALUES (?, ?, 'waived', 'impl:missing', ?, 'reconcile-script', ?, 1)
                """,
                (PROJECT_ID, entry["node_id"], evidence, now),
            )
            inserted += 1
        except sqlite3.IntegrityError:
            # Already exists (race condition guard)
            pass
    conn.commit()
    return inserted


def main(argv=None):
    args = parse_args(argv)

    try:
        db_path = get_db_path(args.workspace)
    except FileNotFoundError as e:
        print(f"ERROR: {e}", file=sys.stderr)
        return 1

    try:
        conn = sqlite3.connect(db_path)
        pm_tasks = fetch_pm_tasks_with_proposed_nodes(conn)
        dropped = find_dropped_nodes(conn, pm_tasks)

        print(f"PM tasks scanned: {len(pm_tasks)}")
        print(f"Dropped nodes found: {len(dropped)}")

        if args.dry_run:
            report_path = generate_report(dropped, args.workspace)
            print(f"Dry-run report written to: {report_path}")
        else:
            inserted = insert_dropped_nodes(conn, dropped)
            print(f"Nodes inserted into node_state: {inserted}")

        conn.close()
        return 0

    except Exception as e:
        print(f"ERROR: {e}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
