"""Auditable graph correction patches for state-only reconcile.

The structural graph is generated by deterministic reconcile.  AI, observer,
or user feedback may propose corrections, but those corrections are stored as
auditable patches and replayed by reconcile instead of mutating the canonical
snapshot in place.
"""
from __future__ import annotations

import copy
import hashlib
import json
import sqlite3
import uuid
from pathlib import PurePosixPath
from typing import Any, Iterable

from .graph_snapshot_store import graph_payload_edges, utc_now


GRAPH_CORRECTION_SCHEMA_SQL = """
CREATE TABLE IF NOT EXISTS graph_correction_patches (
  project_id TEXT NOT NULL,
  patch_id TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'proposed',
  patch_type TEXT NOT NULL,
  risk_level TEXT NOT NULL DEFAULT 'medium',
  base_snapshot_id TEXT NOT NULL DEFAULT '',
  base_commit TEXT NOT NULL DEFAULT '',
  target_node_id TEXT NOT NULL DEFAULT '',
  stable_node_key TEXT NOT NULL DEFAULT '',
  patch_json TEXT NOT NULL DEFAULT '{}',
  evidence_json TEXT NOT NULL DEFAULT '{}',
  created_by TEXT NOT NULL DEFAULT '',
  created_at TEXT NOT NULL DEFAULT '',
  accepted_by TEXT NOT NULL DEFAULT '',
  accepted_at TEXT NOT NULL DEFAULT '',
  last_apply_status TEXT NOT NULL DEFAULT '',
  last_apply_message TEXT NOT NULL DEFAULT '',
  applied_snapshot_id TEXT NOT NULL DEFAULT '',
  updated_at TEXT NOT NULL DEFAULT '',
  PRIMARY KEY(project_id, patch_id)
);

CREATE INDEX IF NOT EXISTS idx_graph_correction_patches_status
  ON graph_correction_patches(project_id, status, patch_type);

CREATE INDEX IF NOT EXISTS idx_graph_correction_patches_target
  ON graph_correction_patches(project_id, target_node_id, stable_node_key);

CREATE TABLE IF NOT EXISTS graph_node_migrations (
  project_id TEXT NOT NULL,
  from_snapshot_id TEXT NOT NULL DEFAULT '',
  to_snapshot_id TEXT NOT NULL,
  old_node_id TEXT NOT NULL,
  new_node_id TEXT NOT NULL,
  change_type TEXT NOT NULL,
  semantic_policy TEXT NOT NULL DEFAULT '',
  feedback_policy TEXT NOT NULL DEFAULT '',
  doc_test_policy TEXT NOT NULL DEFAULT '',
  patch_id TEXT NOT NULL DEFAULT '',
  evidence_json TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL DEFAULT '',
  PRIMARY KEY(
    project_id, from_snapshot_id, to_snapshot_id,
    old_node_id, new_node_id, change_type, patch_id
  )
);

CREATE INDEX IF NOT EXISTS idx_graph_node_migrations_to_snapshot
  ON graph_node_migrations(project_id, to_snapshot_id);
"""

PATCH_STATUS_PROPOSED = "proposed"
PATCH_STATUS_ACCEPTED = "accepted"
PATCH_STATUS_REJECTED = "rejected"
PATCH_STATUS_STALE = "stale"

REPLAYABLE_PATCH_STATUSES = {PATCH_STATUS_ACCEPTED}
ALLOWED_PATCH_STATUSES = {
    PATCH_STATUS_PROPOSED,
    PATCH_STATUS_ACCEPTED,
    PATCH_STATUS_REJECTED,
    PATCH_STATUS_STALE,
}

LOW_RISK_PATCH_TYPES = {
    "mark_package_marker",
    "mark_file_role",
    "move_doc_binding",
    "move_test_binding",
    "add_edge",
    "remove_edge",
}

STRUCTURAL_PATCH_TYPES = {
    "merge_nodes",
    "split_node",
    "reparent_node",
}

ALLOWED_PATCH_TYPES = LOW_RISK_PATCH_TYPES | STRUCTURAL_PATCH_TYPES | {"mark_orphan"}


def ensure_schema(conn: sqlite3.Connection) -> None:
    conn.executescript(GRAPH_CORRECTION_SCHEMA_SQL)


def _json(data: Any) -> str:
    return json.dumps(data if data is not None else {}, ensure_ascii=False, sort_keys=True)


def _json_load(raw: Any, default: Any) -> Any:
    if isinstance(raw, (dict, list)):
        return raw
    if isinstance(raw, str) and raw.strip():
        try:
            value = json.loads(raw)
        except json.JSONDecodeError:
            return default
        return value if value is not None else default
    return default


def _path_list(raw: Any) -> list[str]:
    if raw is None:
        values: Iterable[Any] = []
    elif isinstance(raw, str):
        values = [raw]
    elif isinstance(raw, Iterable):
        values = raw
    else:
        values = [raw]
    out: list[str] = []
    seen: set[str] = set()
    for item in values:
        path = str(item or "").replace("\\", "/").strip("/")
        if path and path not in seen:
            out.append(path)
            seen.add(path)
    return out


def _node_id(node: dict[str, Any]) -> str:
    return str(node.get("id") or node.get("node_id") or "").strip()


def _node_files(node: dict[str, Any], key: str) -> list[str]:
    aliases = {
        "primary": ("primary", "primary_files"),
        "secondary": ("secondary", "secondary_files"),
        "test": ("test", "test_files"),
    }
    for name in aliases.get(key, (key,)):
        if name in node:
            return _path_list(node.get(name))
    return []


def _set_node_files(node: dict[str, Any], key: str, files: list[str]) -> None:
    aliases = {
        "primary": ("primary", "primary_files"),
        "secondary": ("secondary", "secondary_files"),
        "test": ("test", "test_files"),
    }
    present = [name for name in aliases.get(key, (key,)) if name in node]
    target = present[0] if present else aliases.get(key, (key,))[0]
    node[target] = _path_list(files)


def _metadata(node: dict[str, Any]) -> dict[str, Any]:
    metadata = node.setdefault("metadata", {})
    if not isinstance(metadata, dict):
        metadata = {}
        node["metadata"] = metadata
    return metadata


def _append_unique(values: list[str], item: str) -> list[str]:
    if item and item not in values:
        values.append(item)
    return values


def stable_node_key(node: dict[str, Any]) -> str:
    """Return a deterministic node key that survives L-id renumbering."""
    metadata = node.get("metadata") if isinstance(node.get("metadata"), dict) else {}
    module = str(metadata.get("module") or "").strip()
    role = str(metadata.get("file_role") or metadata.get("kind") or node.get("kind") or "").strip()
    primary = "|".join(_node_files(node, "primary"))
    layer = str(node.get("layer") or "").strip()
    title = str(node.get("title") or "").strip()
    raw = f"{module}|{primary}|{layer}|{role}|{title}"
    return hashlib.sha256(raw.encode("utf-8")).hexdigest()


def _basename(path: str) -> str:
    return PurePosixPath(path.replace("\\", "/")).name.lower()


def _suffix(path: str) -> str:
    return PurePosixPath(path.replace("\\", "/")).suffix.lower()


def classify_node_file_role(node: dict[str, Any]) -> dict[str, Any]:
    """Classify source/file role with language-aware hints and generic fallback."""
    layer = str(node.get("layer") or "").upper()
    primary = _node_files(node, "primary")
    secondary = _node_files(node, "secondary")
    tests = _node_files(node, "test")
    metadata = node.get("metadata") if isinstance(node.get("metadata"), dict) else {}
    function_count = int(metadata.get("function_count") or 0)
    typed_relations = metadata.get("typed_relations") if isinstance(metadata.get("typed_relations"), list) else []
    reasons: list[str] = []
    flags: list[str] = []

    if layer in {"L1", "L2", "L3"}:
        return {
            "role": "container",
            "confidence": 1.0,
            "reasons": ["hierarchy container layer"],
            "flags": [],
        }
    if not primary:
        return {
            "role": "container_or_aggregate",
            "confidence": 0.72,
            "reasons": ["no primary source files attached"],
            "flags": ["no_primary_files"],
        }

    names = [_basename(path) for path in primary]
    suffixes = {_suffix(path) for path in primary}
    first = names[0]

    role = "implementation"
    confidence = 0.65

    if first in {"__init__.py", "package-info.java", "module-info.java"}:
        role = "package_marker"
        confidence = 0.94 if function_count == 0 and not typed_relations else 0.78
        reasons.append(f"{first} is a package or module marker")
    elif first in {"index.js", "index.ts", "index.jsx", "index.tsx", "mod.rs"}:
        role = "barrel_or_index"
        confidence = 0.72
        reasons.append(f"{first} is a common index/barrel file")
    elif first in {"main.py", "main.go", "main.rs", "main.cpp", "server.py", "app.py", "cli.py"}:
        role = "runtime_entry"
        confidence = 0.75
        reasons.append(f"{first} is a common runtime entry file")
    elif first in {
        "package.json",
        "pyproject.toml",
        "cargo.toml",
        "go.mod",
        "pom.xml",
        "build.gradle",
        "cmakelists.txt",
    }:
        role = "config_contract"
        confidence = 0.86
        reasons.append(f"{first} is a build/package config contract")
    elif first in {"readme.md", "index.md"} or suffixes <= {".md", ".rst"}:
        role = "doc_index"
        confidence = 0.84
        reasons.append("primary file is documentation/index material")
    elif suffixes & {".h", ".hpp", ".hh", ".hxx"} and not (suffixes & {".c", ".cc", ".cpp", ".cxx"}):
        role = "public_api_surface"
        confidence = 0.72
        reasons.append("header/interface file can be a public API surface")

    if function_count == 0 and not typed_relations:
        flags.append("no_symbols_or_typed_relations")
    if role in {"package_marker", "barrel_or_index", "doc_index"} and (secondary or tests):
        flags.append("coverage_noise_candidate")
    if role == "implementation" and function_count == 0 and not typed_relations:
        flags.append("isolated_or_structural_file_candidate")
        confidence = min(confidence, 0.6)
        reasons.append("implementation-like file has no captured symbols or typed relations")
    if not reasons:
        reasons.append("default implementation role from primary source file")

    return {
        "role": role,
        "confidence": round(confidence, 3),
        "reasons": reasons,
        "flags": flags,
    }


def annotate_graph_node_roles(graph_json: dict[str, Any]) -> dict[str, Any]:
    graph = copy.deepcopy(graph_json if isinstance(graph_json, dict) else {})
    nodes = graph.get("deps_graph", {}).get("nodes", [])
    changed = 0
    role_counts: dict[str, int] = {}
    flag_counts: dict[str, int] = {}
    for node in nodes if isinstance(nodes, list) else []:
        if not isinstance(node, dict):
            continue
        role = classify_node_file_role(node)
        metadata = _metadata(node)
        metadata["file_role"] = role["role"]
        metadata["file_role_confidence"] = role["confidence"]
        metadata["file_role_reasons"] = role["reasons"]
        metadata["quality_flags"] = sorted(set(_path_list(metadata.get("quality_flags")) + role["flags"]))
        if role["role"] == "package_marker":
            metadata["exclude_as_feature"] = True
        role_counts[role["role"]] = role_counts.get(role["role"], 0) + 1
        for flag in role["flags"]:
            flag_counts[flag] = flag_counts.get(flag, 0) + 1
        changed += 1
    return {
        "graph": graph,
        "report": {
            "annotated_nodes": changed,
            "role_counts": role_counts,
            "flag_counts": flag_counts,
        },
    }


def annotate_graph_relationship_metrics(graph_json: dict[str, Any]) -> dict[str, Any]:
    graph = copy.deepcopy(graph_json if isinstance(graph_json, dict) else {})
    nodes = graph.get("deps_graph", {}).get("nodes", [])
    node_map = {_node_id(node): node for node in nodes or [] if isinstance(node, dict) and _node_id(node)}
    metrics: dict[str, dict[str, int]] = {
        node_id: {"fan_in": 0, "fan_out": 0, "hierarchy_in": 0, "hierarchy_out": 0}
        for node_id in node_map
    }
    for edge in graph_payload_edges(graph):
        src = str(edge.get("src") or "")
        dst = str(edge.get("dst") or "")
        edge_type = str(edge.get("edge_type") or edge.get("type") or "")
        direction = str(edge.get("direction") or "")
        if not src or not dst:
            continue
        if edge_type == "contains" or direction == "hierarchy":
            if src in metrics:
                metrics[src]["hierarchy_out"] += 1
            if dst in metrics:
                metrics[dst]["hierarchy_in"] += 1
            continue
        if src in metrics:
            metrics[src]["fan_out"] += 1
        if dst in metrics:
            metrics[dst]["fan_in"] += 1
    isolated_count = 0
    for node_id, node in node_map.items():
        metadata = _metadata(node)
        metadata["graph_metrics"] = metrics[node_id]
        if (
            str(node.get("layer") or "").upper() == "L7"
            and metrics[node_id]["fan_in"] == 0
            and metrics[node_id]["fan_out"] == 0
        ):
            flags = _path_list(metadata.get("quality_flags"))
            _append_unique(flags, "no_direct_dependency_edges")
            metadata["quality_flags"] = flags
            isolated_count += 1
    return {
        "graph": graph,
        "report": {
            "metric_nodes": len(node_map),
            "isolated_l7_count": isolated_count,
        },
    }


def create_patch(
    conn: sqlite3.Connection,
    project_id: str,
    *,
    patch_type: str,
    patch_json: dict[str, Any],
    evidence: dict[str, Any] | None = None,
    patch_id: str | None = None,
    status: str = PATCH_STATUS_PROPOSED,
    risk_level: str = "medium",
    base_snapshot_id: str = "",
    base_commit: str = "",
    target_node_id: str = "",
    stable_key: str = "",
    created_by: str = "",
) -> dict[str, Any]:
    ensure_schema(conn)
    if patch_type not in ALLOWED_PATCH_TYPES:
        raise ValueError(f"unsupported graph correction patch type: {patch_type}")
    if status not in ALLOWED_PATCH_STATUSES:
        raise ValueError(f"invalid graph correction patch status: {status}")
    pid = patch_id or f"gcp-{uuid.uuid4().hex[:12]}"
    now = utc_now()
    conn.execute(
        """
        INSERT INTO graph_correction_patches
          (project_id, patch_id, status, patch_type, risk_level,
           base_snapshot_id, base_commit, target_node_id, stable_node_key,
           patch_json, evidence_json, created_by, created_at, updated_at)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        ON CONFLICT(project_id, patch_id) DO UPDATE SET
          status = excluded.status,
          patch_type = excluded.patch_type,
          risk_level = excluded.risk_level,
          base_snapshot_id = excluded.base_snapshot_id,
          base_commit = excluded.base_commit,
          target_node_id = excluded.target_node_id,
          stable_node_key = excluded.stable_node_key,
          patch_json = excluded.patch_json,
          evidence_json = excluded.evidence_json,
          updated_at = excluded.updated_at
        """,
        (
            project_id,
            pid,
            status,
            patch_type,
            risk_level,
            base_snapshot_id,
            base_commit,
            target_node_id,
            stable_key,
            _json(patch_json),
            _json(evidence or {}),
            created_by,
            now,
            now,
        ),
    )
    return {
        "project_id": project_id,
        "patch_id": pid,
        "status": status,
        "patch_type": patch_type,
        "risk_level": risk_level,
    }


def accept_patch(
    conn: sqlite3.Connection,
    project_id: str,
    patch_id: str,
    *,
    accepted_by: str = "",
) -> bool:
    ensure_schema(conn)
    now = utc_now()
    cur = conn.execute(
        """
        UPDATE graph_correction_patches
        SET status = ?,
            accepted_by = ?,
            accepted_at = ?,
            updated_at = ?
        WHERE project_id = ? AND patch_id = ? AND status = ?
        """,
        (PATCH_STATUS_ACCEPTED, accepted_by, now, now, project_id, patch_id, PATCH_STATUS_PROPOSED),
    )
    return bool(cur.rowcount)


def reject_patch(
    conn: sqlite3.Connection,
    project_id: str,
    patch_id: str,
    *,
    rejected_by: str = "",
    reason: str = "",
) -> bool:
    ensure_schema(conn)
    now = utc_now()
    cur = conn.execute(
        """
        UPDATE graph_correction_patches
        SET status = ?,
            last_apply_status = 'rejected',
            last_apply_message = ?,
            accepted_by = ?,
            updated_at = ?
        WHERE project_id = ? AND patch_id = ? AND status IN (?, ?)
        """,
        (
            PATCH_STATUS_REJECTED,
            reason,
            rejected_by,
            now,
            project_id,
            patch_id,
            PATCH_STATUS_PROPOSED,
            PATCH_STATUS_ACCEPTED,
        ),
    )
    return bool(cur.rowcount)


def list_replayable_patches(conn: sqlite3.Connection, project_id: str) -> list[dict[str, Any]]:
    ensure_schema(conn)
    placeholders = ",".join("?" for _ in REPLAYABLE_PATCH_STATUSES)
    rows = conn.execute(
        f"""
        SELECT *
        FROM graph_correction_patches
        WHERE project_id = ?
          AND status IN ({placeholders})
        ORDER BY accepted_at, created_at, patch_id
        """,
        (project_id, *sorted(REPLAYABLE_PATCH_STATUSES)),
    ).fetchall()
    patches: list[dict[str, Any]] = []
    for row in rows:
        item = dict(row)
        item["patch_json"] = _json_load(item.get("patch_json"), {})
        item["evidence"] = _json_load(item.get("evidence_json"), {})
        patches.append(item)
    return patches


def list_correction_patches(
    conn: sqlite3.Connection,
    project_id: str,
    *,
    statuses: list[str] | None = None,
    patch_type: str = "",
    target_node_id: str = "",
    limit: int = 100,
) -> list[dict[str, Any]]:
    ensure_schema(conn)
    clauses = ["project_id = ?"]
    params: list[Any] = [project_id]
    if statuses:
        clean = [status for status in statuses if status in ALLOWED_PATCH_STATUSES]
        if clean:
            clauses.append("status IN (" + ",".join("?" for _ in clean) + ")")
            params.extend(clean)
    if patch_type:
        clauses.append("patch_type = ?")
        params.append(patch_type)
    if target_node_id:
        clauses.append("target_node_id = ?")
        params.append(target_node_id)
    params.append(max(1, min(int(limit or 100), 1000)))
    rows = conn.execute(
        f"""
        SELECT *
        FROM graph_correction_patches
        WHERE {' AND '.join(clauses)}
        ORDER BY updated_at DESC, created_at DESC, patch_id
        LIMIT ?
        """,
        params,
    ).fetchall()
    out: list[dict[str, Any]] = []
    for row in rows:
        item = dict(row)
        item["patch_json"] = _json_load(item.get("patch_json"), {})
        item["evidence"] = _json_load(item.get("evidence_json"), {})
        out.append(item)
    return out


def correction_patch_summary(conn: sqlite3.Connection, project_id: str) -> dict[str, Any]:
    ensure_schema(conn)
    by_status = {
        str(row["status"]): int(row["cnt"])
        for row in conn.execute(
            """
            SELECT status, COUNT(*) AS cnt
            FROM graph_correction_patches
            WHERE project_id = ?
            GROUP BY status
            """,
            (project_id,),
        ).fetchall()
    }
    by_type = {
        str(row["patch_type"]): int(row["cnt"])
        for row in conn.execute(
            """
            SELECT patch_type, COUNT(*) AS cnt
            FROM graph_correction_patches
            WHERE project_id = ?
            GROUP BY patch_type
            """,
            (project_id,),
        ).fetchall()
    }
    by_risk = {
        str(row["risk_level"]): int(row["cnt"])
        for row in conn.execute(
            """
            SELECT risk_level, COUNT(*) AS cnt
            FROM graph_correction_patches
            WHERE project_id = ?
            GROUP BY risk_level
            """,
            (project_id,),
        ).fetchall()
    }
    last_apply_status = {
        str(row["last_apply_status"]): int(row["cnt"])
        for row in conn.execute(
            """
            SELECT last_apply_status, COUNT(*) AS cnt
            FROM graph_correction_patches
            WHERE project_id = ? AND last_apply_status != ''
            GROUP BY last_apply_status
            """,
            (project_id,),
        ).fetchall()
    }
    accepted = int(by_status.get(PATCH_STATUS_ACCEPTED, 0))
    high_risk_proposed = int(
        conn.execute(
            """
            SELECT COUNT(*)
            FROM graph_correction_patches
            WHERE project_id = ? AND status = ? AND risk_level = 'high'
            """,
            (project_id, PATCH_STATUS_PROPOSED),
        ).fetchone()[0]
    )
    return {
        "total": sum(by_status.values()),
        "by_status": by_status,
        "by_type": by_type,
        "by_risk": by_risk,
        "last_apply_status": last_apply_status,
        "proposed_count": int(by_status.get(PATCH_STATUS_PROPOSED, 0)),
        "accepted_count": accepted,
        "rejected_count": int(by_status.get(PATCH_STATUS_REJECTED, 0)),
        "stale_count": int(by_status.get(PATCH_STATUS_STALE, 0)),
        "replayable_count": accepted,
        "high_risk_proposed_count": high_risk_proposed,
    }


def _node_map(nodes: list[dict[str, Any]]) -> dict[str, dict[str, Any]]:
    return {_node_id(node): node for node in nodes if isinstance(node, dict) and _node_id(node)}


def _find_node(nodes_by_id: dict[str, dict[str, Any]], patch: dict[str, Any]) -> dict[str, Any] | None:
    payload = patch.get("patch_json") if isinstance(patch.get("patch_json"), dict) else {}
    target = str(
        payload.get("target_node_id")
        or patch.get("target_node_id")
        or payload.get("node_id")
        or ""
    )
    if target and target in nodes_by_id:
        return nodes_by_id[target]
    stable = str(patch.get("stable_node_key") or payload.get("stable_node_key") or "")
    if stable:
        for node in nodes_by_id.values():
            if stable_node_key(node) == stable:
                return node
    return None


def _remove_edge(edges: list[dict[str, Any]], *, src: str, dst: str, edge_type: str) -> int:
    before = len(edges)
    edges[:] = [
        edge for edge in edges
        if not (
            str(edge.get("src") or edge.get("source") or "") == src
            and str(edge.get("dst") or edge.get("target") or "") == dst
            and str(edge.get("edge_type") or edge.get("type") or "depends_on") == edge_type
        )
    ]
    return before - len(edges)


def _add_edge(edges: list[dict[str, Any]], edge: dict[str, Any]) -> bool:
    src = str(edge.get("src") or edge.get("source") or "")
    dst = str(edge.get("dst") or edge.get("target") or "")
    edge_type = str(edge.get("edge_type") or edge.get("type") or "depends_on")
    direction = str(edge.get("direction") or "dependency")
    if not src or not dst:
        return False
    for existing in edges:
        if (
            str(existing.get("src") or existing.get("source") or "") == src
            and str(existing.get("dst") or existing.get("target") or "") == dst
            and str(existing.get("edge_type") or existing.get("type") or "depends_on") == edge_type
            and str(existing.get("direction") or "dependency") == direction
        ):
            return False
    item = dict(edge)
    item["src"] = src
    item["dst"] = dst
    item["edge_type"] = edge_type
    item["direction"] = direction
    edges.append(item)
    return True


def _edge_payload(payload: dict[str, Any]) -> dict[str, Any]:
    edge = payload.get("edge") if isinstance(payload, dict) else {}
    if isinstance(edge, dict) and edge:
        return dict(edge)
    return dict(payload if isinstance(payload, dict) else {})


def _validate_add_edge_payload(
    edge: dict[str, Any],
    nodes_by_id: dict[str, dict[str, Any]],
) -> str:
    src = str(edge.get("src") or edge.get("source") or "")
    dst = str(edge.get("dst") or edge.get("target") or "")
    if not src or not dst:
        return "edge_endpoint_empty"
    if src == dst:
        return "self_edge_not_allowed"
    if src not in nodes_by_id or dst not in nodes_by_id:
        return "edge_endpoint_missing"
    return ""


def _validate_remove_edge_payload(edge: dict[str, Any]) -> str:
    src = str(edge.get("src") or edge.get("source") or "")
    dst = str(edge.get("dst") or edge.get("target") or "")
    if not src or not dst:
        return "edge_endpoint_empty"
    return ""


def apply_correction_patches(
    graph_json: dict[str, Any],
    patches: list[dict[str, Any]],
    *,
    from_snapshot_id: str = "",
    to_snapshot_id: str = "",
) -> dict[str, Any]:
    """Replay accepted patches onto a graph copy and return graph + audit."""
    graph = copy.deepcopy(graph_json if isinstance(graph_json, dict) else {})
    deps = graph.setdefault("deps_graph", {})
    if not isinstance(deps, dict):
        deps = {}
        graph["deps_graph"] = deps
    nodes = deps.setdefault("nodes", [])
    edges = deps.setdefault("edges", [])
    if not isinstance(nodes, list):
        nodes = []
        deps["nodes"] = nodes
    if not isinstance(edges, list):
        edges = []
        deps["edges"] = edges
    nodes_by_id = _node_map(nodes)
    applied: list[dict[str, Any]] = []
    stale: list[dict[str, Any]] = []
    migrations: list[dict[str, Any]] = []

    for patch in patches:
        patch_id = str(patch.get("patch_id") or "")
        patch_type = str(patch.get("patch_type") or "")
        payload = patch.get("patch_json") if isinstance(patch.get("patch_json"), dict) else {}
        node = _find_node(nodes_by_id, patch)
        target_id = _node_id(node) if node else str(payload.get("target_node_id") or patch.get("target_node_id") or "")
        if patch_type not in ALLOWED_PATCH_TYPES:
            stale.append({"patch_id": patch_id, "status": "unsupported_patch_type", "patch_type": patch_type})
            continue

        if patch_type in {"mark_package_marker", "mark_file_role", "mark_orphan"}:
            if not node:
                stale.append({"patch_id": patch_id, "status": "target_node_missing", "patch_type": patch_type})
                continue
            metadata = _metadata(node)
            role = str(payload.get("file_role") or ("package_marker" if patch_type == "mark_package_marker" else "unknown"))
            if patch_type == "mark_orphan":
                role = str(payload.get("file_role") or metadata.get("file_role") or "orphan_candidate")
                flags = _path_list(metadata.get("quality_flags"))
                _append_unique(flags, "orphan_candidate")
                metadata["quality_flags"] = flags
            metadata["file_role"] = role
            metadata["file_role_confidence"] = float(payload.get("confidence") or metadata.get("file_role_confidence") or 1.0)
            if patch_type == "mark_package_marker":
                metadata["exclude_as_feature"] = True
                flags = _path_list(metadata.get("quality_flags"))
                _append_unique(flags, "coverage_noise_candidate")
                metadata["quality_flags"] = flags
            metadata.setdefault("graph_correction_patches", [])
            _append_unique(metadata["graph_correction_patches"], patch_id)
            applied.append({"patch_id": patch_id, "status": "applied", "target_node_id": target_id})
            migrations.append({
                "old_node_id": target_id,
                "new_node_id": str(payload.get("new_node_id") or target_id),
                "change_type": patch_type,
                "semantic_policy": str(payload.get("semantic_policy") or "keep_if_hash_matches"),
                "feedback_policy": str(payload.get("feedback_policy") or "keep_on_node"),
                "doc_test_policy": str(payload.get("doc_test_policy") or "recalculate_coverage"),
                "patch_id": patch_id,
                "evidence": patch.get("evidence") or {},
            })
            continue

        if patch_type in {"move_doc_binding", "move_test_binding"}:
            src_node = node
            dst_id = str(payload.get("destination_node_id") or payload.get("new_node_id") or "")
            dst_node = nodes_by_id.get(dst_id)
            key = "secondary" if patch_type == "move_doc_binding" else "test"
            files = _path_list(payload.get("files"))
            if not src_node or not dst_node or not files:
                stale.append({"patch_id": patch_id, "status": "binding_target_missing", "patch_type": patch_type})
                continue
            src_files = [f for f in _node_files(src_node, key) if f not in files]
            dst_files = _node_files(dst_node, key)
            for file_path in files:
                _append_unique(dst_files, file_path)
            _set_node_files(src_node, key, src_files)
            _set_node_files(dst_node, key, dst_files)
            applied.append({"patch_id": patch_id, "status": "applied", "target_node_id": target_id, "destination_node_id": dst_id})
            migrations.append({
                "old_node_id": target_id,
                "new_node_id": dst_id,
                "change_type": patch_type,
                "semantic_policy": "keep_on_source",
                "feedback_policy": "keep_on_source",
                "doc_test_policy": "move_binding",
                "patch_id": patch_id,
                "evidence": {"files": files, **(patch.get("evidence") or {})},
            })
            continue

        if patch_type == "add_edge":
            edge = _edge_payload(payload)
            status = _validate_add_edge_payload(edge, nodes_by_id)
            if status:
                stale.append({"patch_id": patch_id, "status": status, "patch_type": patch_type})
                continue
            src = str(edge.get("src") or edge.get("source") or "")
            dst = str(edge.get("dst") or edge.get("target") or "")
            edge.setdefault("evidence", {"source": "graph_correction_patch", "patch_id": patch_id})
            added = _add_edge(edges, edge)
            applied.append({"patch_id": patch_id, "status": "applied" if added else "already_present", "src": src, "dst": dst})
            continue

        if patch_type == "remove_edge":
            edge = _edge_payload(payload)
            status = _validate_remove_edge_payload(edge)
            if status:
                stale.append({"patch_id": patch_id, "status": status, "patch_type": patch_type})
                continue
            src = str(edge.get("src") or edge.get("source") or "")
            dst = str(edge.get("dst") or edge.get("target") or "")
            edge_type = str(edge.get("edge_type") or edge.get("type") or "depends_on")
            removed = _remove_edge(edges, src=src, dst=dst, edge_type=edge_type)
            applied.append({"patch_id": patch_id, "status": "applied" if removed else "not_present", "src": src, "dst": dst})
            continue

        stale.append({"patch_id": patch_id, "status": "structural_patch_requires_dedicated_apply", "patch_type": patch_type})

    report = {
        "from_snapshot_id": from_snapshot_id,
        "to_snapshot_id": to_snapshot_id,
        "candidate_patch_count": len(patches),
        "applied_count": len(applied),
        "stale_count": len(stale),
        "applied": applied,
        "stale": stale,
        "migrations": migrations,
    }
    graph.setdefault("metadata", {})
    if isinstance(graph["metadata"], dict):
        graph["metadata"]["graph_correction_patch_report"] = {
            "applied_count": report["applied_count"],
            "stale_count": report["stale_count"],
            "to_snapshot_id": to_snapshot_id,
        }
    return {"graph": graph, "report": report}


def persist_node_migrations(
    conn: sqlite3.Connection,
    project_id: str,
    *,
    from_snapshot_id: str,
    to_snapshot_id: str,
    migrations: list[dict[str, Any]],
) -> int:
    ensure_schema(conn)
    now = utc_now()
    count = 0
    for migration in migrations:
        old_id = str(migration.get("old_node_id") or "")
        new_id = str(migration.get("new_node_id") or "")
        change_type = str(migration.get("change_type") or "")
        if not old_id or not new_id or not change_type:
            continue
        conn.execute(
            """
            INSERT OR REPLACE INTO graph_node_migrations
              (project_id, from_snapshot_id, to_snapshot_id, old_node_id, new_node_id,
               change_type, semantic_policy, feedback_policy, doc_test_policy,
               patch_id, evidence_json, created_at)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """,
            (
                project_id,
                from_snapshot_id,
                to_snapshot_id,
                old_id,
                new_id,
                change_type,
                str(migration.get("semantic_policy") or ""),
                str(migration.get("feedback_policy") or ""),
                str(migration.get("doc_test_policy") or ""),
                str(migration.get("patch_id") or ""),
                _json(migration.get("evidence") or {}),
                now,
            ),
        )
        count += 1
    return count


def record_patch_apply_report(
    conn: sqlite3.Connection,
    project_id: str,
    *,
    snapshot_id: str,
    report: dict[str, Any],
) -> dict[str, int]:
    ensure_schema(conn)
    now = utc_now()
    applied_count = 0
    stale_count = 0
    for item in report.get("applied") or []:
        patch_id = str(item.get("patch_id") or "")
        if not patch_id:
            continue
        conn.execute(
            """
            UPDATE graph_correction_patches
            SET last_apply_status = ?,
                last_apply_message = ?,
                applied_snapshot_id = ?,
                updated_at = ?
            WHERE project_id = ? AND patch_id = ?
            """,
            (
                str(item.get("status") or "applied"),
                _json(item),
                snapshot_id,
                now,
                project_id,
                patch_id,
            ),
        )
        applied_count += 1
    for item in report.get("stale") or []:
        patch_id = str(item.get("patch_id") or "")
        if not patch_id:
            continue
        conn.execute(
            """
            UPDATE graph_correction_patches
            SET status = ?,
                last_apply_status = ?,
                last_apply_message = ?,
                applied_snapshot_id = ?,
                updated_at = ?
            WHERE project_id = ? AND patch_id = ?
            """,
            (
                PATCH_STATUS_STALE,
                str(item.get("status") or "stale"),
                _json(item),
                snapshot_id,
                now,
                project_id,
                patch_id,
            ),
        )
        stale_count += 1
    return {"applied": applied_count, "stale": stale_count}
